apps:
    script: /home/igrej3682/applications/ibadejuf_ead/index.js
    name: ibadejuf_ead
    max_memory_restart: 128M
    exec_mode: fork
    ignore_watch: '["[\/\]\./", "node_modules"]'
    watch: false
    log_date_format: 'YYYY-MM-DD HH:mm Z'
    out_file: /home/igrej3682/applications/ibadejuf_ead/stdout.log
    error_file: /home/igrej3682/applications/ibadejuf_ead/stdout.log
    pid_file: /home/igrej3682/applications/ibadejuf_ead/pid.pid
    interpreter: /usr/nodejs/node-v22.2.0/bin/node
    env: { NODE_ENV: production, PORT: '51689' }
